[package]
name = "rust-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spake2 = "0.3.1"
aes = "0.8.2"
block-padding = "0.2.1"
indicatif = "0.15.0"
sha2 = "0.10.1"
hkdf = "0.12.3"
